from .objects.drone import TelloDrone
from .. import cache

drone = TelloDrone()

import logging
import av #for adjustment of log level
drone.LOGGER.setLevel(logging.ERROR)
# removing verbose ffmpeg output generated by ffmpeg 
av.logging.set_level(0)

from .routes import tello_routes, tello_automation_routes

def __del__(self):
    drone.land()
    drone.end()